services:
  # Base de données PostgreSQL
  database:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./healthAI-database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  # API Backend (Express / Node)
  api_backend:
    build:
      context: ./healthAI-backend-API
      dockerfile: Dockerfile
    container_name: api_backend
    env_file:
      - .env
    volumes:
      - ./healthAI-backend-API:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app_network
    command: npm run dev
    restart: unless-stopped

  # ETL Backend (Python + FastAPI)
  etl_backend:
    build:
      context: ./healthAI-backend-ETL
      dockerfile: Dockerfile
    container_name: etl_backend
    env_file:
      - ./healthAI-backend-ETL/.env
    volumes:
      - ./healthAI-backend-ETL:/app
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Frontend Angular
  frontend:
    build:
      context: ./healthAI-frontend
      dockerfile: Dockerfile
    container_name: angular_frontend
    volumes:
      - ./healthAI-frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - api_backend
    networks:
      - app_network
    command: npm start


volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge